### ISSUE TITLE
Make installation of all Docker images on the host/VM optional

### ISSUE THREAD

**Issue by olberger** [mfthomps/Labtainers#3]
The installation scripts install by default all docker images.

While this may be better for a single VM made available to all students at once for deployment constraints (or offline use), this makes the installation unnecessary big for contexts where only one lab will be executed.

I'd prefer that the default behaviour of the installer is to only download the base image, and make it an option to install everything, for instance for the provisioning of the reference VM.

**Comment by mfthomps** [comment]
The installation only installs the base images -- though there are several of them.  Docker images for the individual labs are pulled the first time the lab is run (but since the base images are already there, the per-lab wait time is reduced.)  There are trade-offs, e.g., do we need a centos and lamp as baselines?  We opted for that so the student does not endure long download times when trying to run a new lab.
