### ISSUE TITLE
Suggestion for db-access lab

### ISSUE THREAD

**Issue by jjwhit** [mfthomps/Labtainers#47]
Now that I have assigned and graded the db-access lab, I have a suggestion that may help the students get more out of the lab. 

In my world students may not have taken a database course as a prerequisite (and whatever I knew about sql db is gotten pretty rusty). This leads to two issues: (1) it is hard for students to get the big picture for the database and its tables and the role of db admin, plus (2) students do a lot of trial and error before they are successful in issuing sql commands to grant, revoke and verify user permissions.  

My suggestion to help with issue #1 is to include mysql-workbench on the db-admin system and start it as part of the lab. This will give the students the full perspective on the database, the tables and the users.  Students can still use command line interface before and after the admin changes are made to verify their privileges.

**Comment by mfthomps** [comment]
Great suggestion.  My plan is to make its use optional in the lab manual, and tell students the command to start it (if they wish).   And the database computer will have a .mysql/workbench profile that includes an "admin" user so the student does not need to add a connection to workbench (since we don't use a root user).

**Comment by mfthomps** [comment]
Now part of the latest Labtainers release.
