### ISSUE TITLE
Self-hosted macs-hash: `lynx verydodgy.com` unable to connect

### ISSUE THREAD

**Issue by Dissfall** [mfthomps/Labtainers#89]
Environment: self-hosted Labtainers on Google Cloud

When trying open verydodgy.com through `lynx` it says `unable to connect` but works with every other site.

![CleanShot 2024-09-23 at 13 00 44](https://github.com/user-attachments/assets/0c5d6e80-85fc-422c-93d5-ed6e26a1ee95)

**Comment by mfthomps** [comment]
My guess is that google is blocking that address.
I'll update the lab manual to note this will not work on systems lacking internet, and systems that block sites like verydodgy.com, including the gcloud.  The correct fix will be to change the lab to have its own web server so that there is no need to reach out.

Thank you for the report.

**Comment by mfthomps** [comment]
This should now be fixed.  You will need to update your labtainers_google scripts with https://raw.githubusercontent.com/mfthomps/Labtainers/master/google/install_labtainers.sh
